boxes = [
  { name: "jammy", box: "ubuntu/jammy64" },
  { name: "resolute", box: "cloud-image/ubuntu-26.04" }
]

Vagrant.configure("2") do |config|
  boxes.each do |opts|
    config.vm.define opts[:name] do |node|
      node.vm.box = opts[:box]
      
      # Enable X11 forwarding to test the GUI on your host machine
      node.ssh.forward_x11 = true 
      
      # Mount the scripts folder
      node.vm.synced_folder ".", "/home/vagrant/scripts"
      # Mount the assets folder (assumed to be one level up from scripts)
      node.vm.synced_folder "../.assets", "/home/vagrant/.assets"

      # Install GUI dependencies missing in the minimal server box
      node.vm.provision "shell", inline: <<-SHELL
        apt-get update
        apt-get install -y libxrender1 libxtst6 libxi6 libfontconfig1 libgtk-3-0
      SHELL

      # Increase memory to handle Android Studio comfortably
      node.vm.provider "virtualbox" do |vb|
        vb.memory = "4096"
        vb.cpus = 2
      end
    end
  end
end
